name: Start demo dev server

runs:
  using: composite
  steps:
    - name: "Build assets"
      run: bundle exec rake assets:precompile
      shell: bash

    - name: "Start local server"
      run: bundle exec rake server -d
      shell: bash
      env:
        CANONICAL_HOST: 172.17.0.1:3000
        SECRET_KEY_BASE: placeholdersecretkeybase
        RAILS_ENV: production
        RACK_ENV: production
        RAILS_LOG_TO_STDOUT: "true"
        RAILS_SERVE_STATIC_FILES: "true"
