name: Lint
on:
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  lint-demo-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: demo

      - name: "Ruby lint"
        run: bundle exec rubocop --format progress --format github

  lint-engine:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: engine
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: engine

      - name: "Ruby lint"
        run: bundle exec rubocop --format progress --format github

  audit-demo-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
    needs: lint-demo-app
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: demo

      - name: "Bundle audit"
        run: bundle exec bundle-audit

      - name: "Brakeman audit"
        run: bundle exec brakeman

  audit-engine:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: engine
    needs: lint-engine
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: engine

      - name: "Bundle audit"
        run: bundle exec bundle-audit

      - name: "Brakeman audit"
        run: bundle exec brakeman